# docker-compose.yml
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mixedvoices
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/mixedvoices
      REDIS_URL: redis://redis:6379/0
      FLASK_APP: mixedvoices.server
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: 5001
      TRANSCRIPTION_SERVICE_URL: http://transcription-service:5002
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python -m flask run --host=0.0.0.0 --port=5001

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/mixedvoices
      REDIS_URL: redis://redis:6379/0
      TRANSCRIPTION_SERVICE_URL: http://transcription-service:5002
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A mixedvoices.tasks worker --loglevel=info

  transcription-service:
    build:
      context: .
      dockerfile: Dockerfile.transcription
    ports:
      - "5002:5002"
    environment:
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}  # Optional, for API fallback
    volumes:
      - model_cache:/root/.cache  # Cache for all ML models
    command: python -m flask run --host=0.0.0.0 --port=5002

volumes:
  postgres_data:
  model_cache: