# docker-compose.dev.yml (development overrides)
services:
  web:
    build:
      target: development
    environment:
      FLASK_DEBUG: 1
    volumes:
      - .:/app
    
  worker:
    build:
      target: development
    volumes:
      - .:/app